language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_903ff9f80be0_key -iv $encrypted_903ff9f80be0_iv
  -in My\ Project-54ed4b23d713.json.enc -out My\ Project-54ed4b23d713.json
  -d
- export GOOGLE_APPLICATION_CREDENTIALS="My\ Project-54ed4b23d713.json"
- cat %GOOGLE_APPLICATION_CREDENTIALS
install:
- pip install -r requirements.txt
script:
- pytest test/ndb_test.py
